# Base app default config 

default: &default
  foo: 'default_foo'

development:
  <<: *default
  foo: development_foo

test:
  <<: *default
  foo: test_foo

production:
  <<: *default
  foo: production_foo