# config for database

default: &default
  database_url: <%= ENV.fetch('DATABASE_URL') %>

development:
  <<: *default
  database_url: <%= ENV.fetch('DATABASE_URL') %>

test:
  <<: *default
  database_url: <%= ENV.fetch('DATABASE_URL') %>

production:
  <<: *default
  database_url: <%= ENV.fetch('DATABASE_URL') %>
